server:
  port: 8761

eureka:
  client:
    service-url:
#      defaultZone: http://icode-msp-eureka-service:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: icode-msp-eureka-service

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF